#!/usr/bin/env bash
# this script configs and installs nginx then redirects to a new site

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 80
sudo ufw allow 22
sudo ufw enable

sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www

# create html file
echo "Hello World!" > /var/www/html/index.html

# permanent move something
# https://stackoverflow.com/questions/11973047/adding-and-using-header-http-in-nginx
str="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sed -i "s/server_name _;/$str/" /etc/nginx/sites-enabled/default

# 404 error setup
echo "Ceci n'est pas une page" > /var/www/html/404.html
new_str="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sed -i "s/listen 80 default_server;/$new_str/" /etc/nginx/sites-enabled/default

# start the nginx
service nginx restart
