#!/usr/bin/env bash
# we kept running out of time so here's a script to print time

hr=0
min=1

while [ $hr -lt 13 ]
do
	echo "Hour: $hr"
	min=1
	while [[ $min -lt 60 ]]
	do
		echo "$min"
		((min++))
	done
	((hr++))
done
