#!/usr/bin/env bash
# this script sets up an Ubuntu server through Docker
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new 	# make a copy of the hosts file
echo "127.0.0.2		localhost" > ~/hosts.new 	# write the new changes to the copy
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts 	# restore the copy
